### ISSUE TITLE
Allow access to the dashboard with a sample created user

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/finance-trade#23]
Give the option to the user to access the dashboard with a pre created a user account that has a portfolio created and setup.

**Comment by VidyasagarMSC** [comment]
Looks like Continue as guest option is not available in auth0. The only other suggestion which I found is this 

> Auth0 has no way of knowing about your user's session in your applications. What you could do is edit your SSO login page to include a "Continue as Guest" button or similar.
> 
> Another option would be to include a value in state when redirecting to /authorize that indicates that the user is logged in as a guest; you would then programatically redirect to a desired URL from your login page.

**Comment by l2fprod** [comment]
Given that for the first phase of the demo we don't need user auth, we should drop the login phase altogether and just put a label "Login as guest" to pretend we are logging in.

**Comment by Twanawebtech** [comment]
I wouldn't agree with removing Auth0 just yet, I did spend time adding that so why to remove it where we will be using it after Ram's demo. Also, I would be looking to compare that with APP ID. 

Here is a guest user I just created.
User: guest@gmail.com
Password: 123456

In the UI, add that user to the HTML page so the user can use that if they want. 

Let's keep it simple.

**Comment by VidyasagarMSC** [comment]
![continue as guest](https://user-images.githubusercontent.com/6552440/28916445-d5e72124-785f-11e7-94d8-58dcbfd1160e.gif)

A few code tweaks and "continue as guest" is available.

**Comment by VidyasagarMSC** [comment]
reopened as Login & continue as guest panels are shown on the home page.
