### ISSUE TITLE
Investment Portfolio service setup

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/finance-trade#4]
Investment Portfolio service - To allow for storing, updating and querying the investment portfolio and holdings under each portfolio.

We need to allow the user to create their own portfolio and then assign a template to it.

**Comment by VidyasagarMSC** [comment]
**Investment-portfolio-fintrade** service + app (required) is created under Dev-Advocates and credentials are used via VCAP_SERVICES to FinTrade app.
