### ISSUE TITLE
Portfolio total values after Simulation completion

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Bluemix/finance-trade#46]
To show the total portfolio Current Price, Stressed Price and Average Profit/ Loss.

**Calculations**
Portfolio Current Price / Stressed Price = (Holding1 CP/SP * Holding1 quantity) + (Holding2 CP/SP * Holding2 quantity).......

Portfolio Profit/Loss = Sum of Holding PL / Total holdings.

**Comment by VidyasagarMSC** [comment]
@robert-hodgson1 Can you pls. evaluate the calculations above?

**Comment by robert-hodgson1** [comment]
Hi,

I hope this is clear but let me know if not.
There are 3 levels to consider; 
1) the instrument (a single unit or quantity =1), this is what is returned by the instrument analytic service
2) the holding (the instrument scaled for the quantity you hold).
3) the portfolio which is the sum of your holdings.

The 4 measures that are relevant are:
Current Price, CP
Stressed Price, SP
P&L% - in percent change between current and stressed relative to current value
P&L$ - as a change in value between current and stressed.

So for the instrument:
CP_i = CP, 
SP_i = SP, 
P&L%_i = 100*(SP/CP-1), 
P&L$_i = SP-CP

each holding
CP_h = Quantity * CP_i
SP_h = Quantity * SP_i
P&L%_h = P&L%_i
P&L$_h = quantity * P&L$_i or SP_h - CP_h

Portfolio - sum is across holdings
CP_p = Sum (CP_h)
SP_p = Sum(SP_h)
P&L%_p = 100*(SP_p/CP_p - 1)
P&L$_p = SUM(P&L_h)  or  CP_p - SP_p

Rob

**Comment by robert-hodgson1** [comment]
@VidyasagarMSC -  hi - let me know if the above is clear? Thanks Rob

**Comment by VidyasagarMSC** [comment]
Thanks @robert-hodgson1 . It's clear now. Can you verify the calculations once? So that we are on the same page.

**Comment by VidyasagarMSC** [comment]
Verified by Rob on call.
