### ISSUE TITLE
Fintrade is serving all files under the app directory - not just the webapp files

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/finance-trade#48]
The root directory of the app is exposed as static content in:
https://github.com/IBM-Bluemix/finance-trade/blob/master/server.js#L92
```
app.use('/', express.static(__dirname +  '/'));
```

This means one can access the backend files like:
http://fintrade.mybluemix.net/server.js
or
http://fintrade.mybluemix.net/logs/staging_task.log

**Comment by VidyasagarMSC** [comment]
Thanks Fred. I am fixing this.

**Comment by VidyasagarMSC** [comment]
Fixed in the latest commit.
