### ISSUE TITLE
News environment and collection IDs need to be created by install

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/finance-trade#53]
https://github.com/IBM-Bluemix/finance-trade/blob/master/server.js#L284

Currently they are hardcoded. They should be specific to the discovery service that is created by the toolchain for this app.

The environment and collection should be created either by the toolchain or by the app.

**Comment by l2fprod** [comment]
It seems that the pre-built "news" collection can be called by using "system" as environment id and "news" as collection id:

```
https://gateway.watsonplatform.net/discovery/api/v1/environments/system/collections/news/query?aggregation=term(enriched_text.sentiment.document.label%2Ccount%3A3)&filter=&version=2017-08-01
```

**Comment by l2fprod** [comment]
Confirmed by this:
https://www.ibm.com/watson/developercloud/doc/discovery/migrate-bwdn.html

The pre-enriched data set now has static IDs.

**Comment by Twanawebtech** [comment]
looks like the system and news not working as expected for Discovery news.
I tried using that and getting the error:     
at emitNone (events.js:91:20) code: 400, error: 'Invalid environment id: system' }

**Comment by l2fprod** [comment]
@Twanawebtech you need to make sure to use the latest version 2017-08-01 when creating the discovery object. We should remove the existing discovery service in our shared space and create a new one to all be in sync.

**Comment by Twanawebtech** [comment]
Yes agreed, doing that now.
