### ISSUE TITLE
Simulated analytics area not visible on the new UI - Safari

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Bluemix/finance-trade#68]
Simulated analytics area not visible on the new UI.  This is only on **Safari** Browser.Looks good on Chrome and Firefox. <img width="1440" alt="screen shot 2017-08-04 at 7 11 57 am" src="https://user-images.githubusercontent.com/6552440/28950797-6213d2f8-78e4-11e7-993a-93e4e14a247d.png">

**Comment by Twanawebtech** [comment]
@VidyasagarMSC can you test this now.

**Comment by VidyasagarMSC** [comment]
Looks good now. Closing the issue
