### ISSUE TITLE
Setup Predictive-Market-Scenarios and Simulated Instrument Analytics

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/finance-trade#7]
Predictive-Market-Scenarios Service - To create a scenario that then can be used by the “Simulated Instrument Analytics.“

Simulated Instrument Analytics - To display analytics on how the news impacted the portfolio

**Comment by VidyasagarMSC** [comment]
The server part (Node) calling the service endpoints are coded and available on the master branch.
